apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
